### ISSUE TITLE
Crash when run in Atom's Install Packages Pane

### ISSUE THREAD

**Issue by MarkHerhold** [TabDigital/atom-mocha-test-runner#28]
I ran `ctrl + shift + m` on the atom install page, resulting in `TypeError: undefined is not a function`. I know that this isn't really an expected use case.

1. Install atom-mocha-test-runner
2. Attempt to run the mocha specs from the atom install pane

**Atom Version**: 0.190.0
**System**: linux 3.16.0-31-generic
**Thrown From**: [mocha-test-runner](https://github.com/TabDigital/atom-mocha-test-runner) package, v0.4.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/mark/.atom/packages/mocha-test-runner/lib/context.coffee:7

TypeError: undefined is not a function
  at Object.exports.find (/home/mark/.atom/packages/mocha-test-runner/lib/context.coffee:7:32)
  at Object.module.exports.run (/home/mark/.atom/packages/mocha-test-runner/lib/mocha-test-runner.coffee:70:30)
  at atom-workspace.subscriptions.add.atom.commands.add.mocha-test-runner:run (/home/mark/.atom/packages/mocha-test-runner/lib/mocha-test-runner.coffee:50:89)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:242:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:521:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
     -4:29.6 core:backspace (atom-text-editor.editor.mini)
     -4:25.8 core:move-down (atom-text-editor.editor.mini)
     -4:16.0 core:confirm (atom-text-editor.editor.mini)
     -4:16.0 application:run-all-specs (div.settings-view.pane-item)
     -3:56.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -3:56.0 core:cancel (atom-text-editor.editor.mini)
     -3:55.2 editor:consolidate-selections (atom-text-editor.editor.mini)
     -3:55.2 core:cancel (atom-text-editor.editor.mini)
  2x -3:45.1 command-palette:toggle (atom-text-editor.editor)
     -0:38.2 core:backspace (atom-text-editor.editor.mini)
     -0:37.9 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini)
  4x -0:35.3 core:move-down (atom-text-editor.editor.mini)
     -0:31.9 core:confirm (atom-text-editor.editor.mini)
     -0:31.9 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -0:25.3 core:confirm (atom-text-editor.editor.mini)
     -0:00.8 mocha-test-runner:run (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "dev-live-reload",
      "language-c",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-beautify, v0.23.4
atomatigit, v1.2.3
css-color-underline, v1.0.1
git-log, v0.3.0
linter, v0.12.0
linter-jshint, v0.1.1
mocha-test-runner, v0.4.0
space-tab, v0.1.0

# Dev
No dev packages
```

**Comment by rprieto** [comment]
Thanks @MarkHerhold for a great bug report! I think it might be due to `mocha-test-runner` assuming there is a current text editor pane. Should be an easy fix.
