### ISSUE TITLE
Support for ES6

### ISSUE THREAD

**Issue by RaviVaranasi** [TabDigital/atom-mocha-test-runner#44]
I tried running the mocha-test-runner with babel but got the following error message

```
Error: only one instance of babel/polyfill is allowed
    at Object.<anonymous> (/Users/playground/cqrs-experiment/node_modules/babel/node_modules/babel-core/lib/polyfill.js:8:9)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/playground/cqrs-experiment/node_modules/mocha-babel/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:161:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/playground/cqrs-experiment/node_modules/babel/node_modules/babel-core/lib/api/register/node-polyfill.js:8:1)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/playground/cqrs-experiment/node_modules/mocha-babel/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:161:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/playground/cqrs-experiment/node_modules/babel/node_modules/babel-core/register.js:1:80)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/playground/cqrs-experiment/node_modules/mocha-babel/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:161:7)

```

**Comment by mschipperheyn** [comment]
+1 es6 is a must have for me. Would be nice if that ran out of the box

**Comment by mschipperheyn** [comment]
Adding --compilers js:babel/register to Options in Settings seems creates other problems for me. 

    /Users/Shared/projects/react/mobile/Base/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);

sigh

**Comment by mghaderyan** [comment]
Guys please remove me from this mailing list

**Comment by kiddkai** [comment]
@mghaderyan you can just unwatch the repo, thanks

**Comment by mghaderyan** [comment]
I can't just manually go to hundreds of repos and do it. It's annoying.
Please do this. I have asked you guys multiple times before

**Comment by rprieto** [comment]
Thanks @RaviVaranasi we'll have a look!
@mghaderyan I'm not sure what you mean. We can't un-watch a repo for you.

**Comment by mghaderyan** [comment]
Hey man. I thought there is a way to remove me from Tab digital list.

**Comment by rprieto** [comment]
I checked and you're not part of the org anymore. Because they're public repos I think you'll have to unwatch them manually, sorry. I'll clean up this thread a bit.

**Comment by mschipperheyn** [comment]
Ok, the solution for me was:

    --compilers js:babel-register

thanks dio_at_getty.io

**Comment by mghaderyan** [comment]
Thanks man.

**Comment by batjko** [comment]
Yea, it works fine with babel, when adding the compiler option:
![image](https://cloud.githubusercontent.com/assets/7287076/14637484/6c88193a-0629-11e6-9b96-569741ec01bf.png)

![image](https://cloud.githubusercontent.com/assets/7287076/14637474/5c9b1748-0629-11e6-888a-e8a5e9f8fd94.png)

**Comment by rprieto** [comment]
Thanks for the update! For anyone else finding this issue, does it mean you had to install https://www.npmjs.com/package/babel-register as a dependency too?

**Comment by batjko** [comment]
@rprieto Yes indeed.

**Comment by KaiHufenbach** [comment]
Hey, 

thanks for the great work!

After setting up mocha + babel for ES6 (don't forgot to setting .babelrc correctly...) the **first** test runs correctly.

When saving mocha test file or associated *.js it still says: `Unexpected token ....` - as with no babel activated. As long as I run mocha from menu, everything is fine. When it's run automatically not.

Any ideas?

.babelrc
`{ "presets": ["es2015"] }`

mocha.opts
`--compilers js:babel-register`

**Comment by eddie** [comment]
To get this working with babel-register 6.5.2 I needed to specify

`--compilers js:babel-core/register`

and not 

`--compilers js:babel-register`

**Comment by mrstux** [comment]
With babel-register 6.18, I added `--compilers js:babel-register` and it worked for me

**Comment by mrstux** [comment]
Would be nice to have this common option as a configuration tickbox

**Comment by rprieto** [comment]
What type of config option do you suggest we add? If it's about `--compilers ...` I think this belongs in `mocha.opts` because they're project-related mocha options. Otherwise we could soon have options for many mocha settings (coffee compiler, recursive tests...).
