### ISSUE TITLE
Uncaught TypeError: editor.getPath is not a function

### ISSUE THREAD

**Issue by ezequielschulman** [TabDigital/atom-mocha-test-runner#46]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [mocha-test-runner](https://github.com/TabDigital/atom-mocha-test-runner) package, v0.4.4

### Stack Trace

Uncaught TypeError: editor.getPath is not a function

```
At /C:/Users/eschulman/.atom/packages/mocha-test-runner/lib/context.coffee:14

TypeError: editor.getPath is not a function
  at Object.exports.find (C:\Users\eschulman\.atom\packages\mocha-test-runner\lib\context.coffee:7:32)
  at Object.module.exports.run (C:\Users\eschulman\.atom\packages\mocha-test-runner\lib\mocha-test-runner.coffee:70:30)
  at atom-workspace.subscriptions.add.atom.commands.add.mocha-test-runner:run (C:\Users\eschulman\.atom\packages\mocha-test-runner\lib\mocha-test-runner.coffee:50:89)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\eschulman\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (C:\Users\eschulman\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\eschulman\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:145:19)
  at EventEmitter.<anonymous> (C:\Users\eschulman\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
     -4:44.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:03.7.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -2:00.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.2.0 mocha-test-runner:run (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
bottom-dock, v0.3.5
grunt-manager, v0.1.9
linter, v1.8.1
linter-jscs, v3.1.0
linter-jshint, v1.2.1
mocha-runner, v1.1.6
mocha-test-runner, v0.4.4
node-debugger, v1.1.8
todo-manager, v0.2.5

# Dev
No dev packages
```

**Comment by mschipperheyn** [comment]
Got this one also. Is this the reason I don't see a settings pane?

**Comment by mschipperheyn** [comment]
Updating Atom fixed this (might have been the restart)

**Comment by mugwump** [comment]
I'm still getting this issue on Atom 1.19.1...

As it is not widely reported, this has probably something to do with a specific project-setup?!

**Comment by mugwump** [comment]
...and uninstalling and re-installing the plugin fixed my problem: Not sure, what was going on there, but it now works again.

**Comment by mugwump** [comment]
...and it has nothing to with atom or the re-install: It's a focus-issue: Running tests, when your focus is in the editor, in the file that contains the test. If your focus is in the project-pane on the file, then the above exception occurs. 

I haven't seen this before, so it appears that somehow the editor.getPath-call has changed in recent atom-versions...
