### ISSUE TITLE
Uncaught TypeError: invalid pid

### ISSUE THREAD

**Issue by afrantz** [TabDigital/atom-mocha-test-runner#55]
Hello,

When i try "ctrl-alt-m" in a testing file, i get this error :

> TypeError: invalid pid
>     at process.kill (node.js:772:15)
>     at killPid (/home/alex/.atom/packages/mocha-test-runner/node_modules/tree-kill/index.js:39:17)
>     at /home/alex/.atom/packages/mocha-test-runner/node_modules/tree-kill/index.js:31:13
>     at Array.forEach (native)
>     at killAll (/home/alex/.atom/packages/mocha-test-runner/node_modules/tree-kill/index.js:23:23)
>     at /home/alex/.atom/packages/mocha-test-runner/node_modules/tree-kill/index.js:16:13
>     at ChildProcess.<anonymous> (/home/alex/.atom/packages/mocha-test-runner/node_modules/tree-kill/index.js:60:17)
>     at ChildProcess.<anonymous> (/home/alex/.atom/packages/mocha-test-runner/node_modules/tree-kill/node_modules/once/once.js:17:15)
>     at emitTwo (events.js:87:13)
>     at ChildProcess.emit (events.js:172:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

Node 0.10.40
Mocha 2.4.5

Thanks in advance,
Alexandre.

**Comment by mcmxc** [comment]
+1

**Comment by SergiiVlasiuk** [comment]
+1
