### ISSUE TITLE
harmony-proxies not working

### ISSUE THREAD

**Issue by mschipperheyn** [TabDigital/atom-mocha-test-runner#57]
https://github.com/mochajs/mocha/issues/1980 

I can't seem to get harmony-proxies to work. Tried adding it to the options for the mocha binary, but no joy

       TypeError: Proxy is not a function
      at _loop (ProxyNormalizr.js:58:18)
      at visitRecord (Project.js:49:24)
      at visitEntity (Project.js:155:20)
      at visit (Project.js:175:12)

Any suggestions?

**Comment by mschipperheyn** [comment]
never mind. If I use Proxy.create, it works

**Comment by rprieto** [comment]
No problem. Happy to close this issue?
