### ISSUE TITLE
Uncaught TypeError: editor.getPath is not a function

### ISSUE THREAD

**Issue by OliverCole** [TabDigital/atom-mocha-test-runner#74]
1. Ran tests from menu.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [mocha-test-runner](https://github.com/TabDigital/atom-mocha-test-runner) package 1.0.0

### Stack Trace

Uncaught TypeError: editor.getPath is not a function

```
At /home/oli/.atom/packages/mocha-test-runner/lib/context.coffee:8

TypeError: editor.getPath is not a function
    at Object.exports.find (/packages/mocha-test-runner/lib/context.coffee:8:32)
    at Object.run (/packages/mocha-test-runner/lib/mocha-test-runner.coffee:75:30)
    at /packages/mocha-test-runner/lib/mocha-test-runner.coffee:55:89)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:10.9.0 timecop:view (atom-pane.pane.active)
  2x -2:39.8.0 core:confirm (input.hidden-input)
  3x -2:13.8.0 core:backspace (input.hidden-input)
     -2:11.6.0 core:confirm (input.hidden-input)
     -0:12.9.0 mocha-test-runner:run (button.btn.icon.enablement.icon-playback-play)
```

### Non-Core Packages

```
mocha-test-runner 1.0.0 
```

**Comment by varuna82** [comment]
any luck with this?
